/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeancasoto_labexamen2;

import java.awt.BorderLayout;
import java.io.File;
import java.io.FileWriter;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeansoto
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarios = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panel_usuario = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        login = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        crear_usuario = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_nombre_usuario = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tf_edad_usuario = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tf_username_usuario = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        pf_password_usuario = new javax.swing.JPasswordField();
        listar_usuario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_usuarios = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        eliminar_usuario = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_usuarios_e = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        albums = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        panel_album = new javax.swing.JPanel();
        crear_album = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tf_nombre_album = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tf_artista_album = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        listar_album = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_album = new javax.swing.JList();
        eliminar_album = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lista_album_e = new javax.swing.JList();
        jButton5 = new javax.swing.JButton();
        cancion = new javax.swing.JDialog();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        combo_cancion = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        tf_nombre_cancion = new javax.swing.JTextField();
        tf_autor_cancion = new javax.swing.JTextField();
        tf_duracion_cancion = new javax.swing.JTextField();
        tf_genero_cancion = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        Login = new javax.swing.JDialog();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        explorar = new javax.swing.JDialog();
        cb_explorar = new javax.swing.JComboBox();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lista_canciones = new javax.swing.JList();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jLabel12.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel12.setText("USUARIOS");

        jLabel13.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel13.setText("Crear ");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel14.setText("Listar");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        panel_usuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));

        javax.swing.GroupLayout panel_usuarioLayout = new javax.swing.GroupLayout(panel_usuario);
        panel_usuario.setLayout(panel_usuarioLayout);
        panel_usuarioLayout.setHorizontalGroup(
            panel_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        panel_usuarioLayout.setVerticalGroup(
            panel_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel15.setText("Eliminar");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout usuariosLayout = new javax.swing.GroupLayout(usuarios.getContentPane());
        usuarios.getContentPane().setLayout(usuariosLayout);
        usuariosLayout.setHorizontalGroup(
            usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addGap(34, 34, 34)
                .addComponent(panel_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(214, 214, 214))
        );
        usuariosLayout.setVerticalGroup(
            usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosLayout.createSequentialGroup()
                .addGroup(usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel13)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel14)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel15))
                    .addGroup(usuariosLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel12)
                        .addGap(52, 52, 52)
                        .addComponent(panel_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel9.setText("Username:");

        jLabel10.setText("Password:");

        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/jeansoto/Downloads/Icono Empresario.png")); // NOI18N

        jButton2.setText("LOG IN");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login.getContentPane());
        login.getContentPane().setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButton2))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(36, 36, 36)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel20.setText("Crear usuario");

        jLabel21.setText("Nombre");

        jLabel22.setText("Edad");

        jLabel23.setText("Username");

        jLabel24.setText("Password");

        jButton3.setText("Crear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crear_usuarioLayout = new javax.swing.GroupLayout(crear_usuario);
        crear_usuario.setLayout(crear_usuarioLayout);
        crear_usuarioLayout.setHorizontalGroup(
            crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_usuarioLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pf_password_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crear_usuarioLayout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(261, 261, 261))
                        .addGroup(crear_usuarioLayout.createSequentialGroup()
                            .addGroup(crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23)
                                .addComponent(jLabel21))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_username_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_edad_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(crear_usuarioLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(87, 87, 87)))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crear_usuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(170, 170, 170))
        );
        crear_usuarioLayout.setVerticalGroup(
            crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_usuarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel20)
                .addGap(56, 56, 56)
                .addGroup(crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_edad_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(34, 34, 34)
                .addGroup(crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_username_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(crear_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf_password_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(24, 24, 24))
        );

        lista_usuarios.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(lista_usuarios);

        jLabel7.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel7.setText("Listar usuarios");

        javax.swing.GroupLayout listar_usuarioLayout = new javax.swing.GroupLayout(listar_usuario);
        listar_usuario.setLayout(listar_usuarioLayout);
        listar_usuarioLayout.setHorizontalGroup(
            listar_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listar_usuarioLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(listar_usuarioLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        listar_usuarioLayout.setVerticalGroup(
            listar_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listar_usuarioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jLabel8.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel8.setText("Eliminar usuarios");

        lista_usuarios_e.setModel(                        new DefaultListModel());
        lista_usuarios_e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_usuarios_eMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lista_usuarios_e);

        jButton1.setText("Eliminar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eliminar_usuarioLayout = new javax.swing.GroupLayout(eliminar_usuario);
        eliminar_usuario.setLayout(eliminar_usuarioLayout);
        eliminar_usuarioLayout.setHorizontalGroup(
            eliminar_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminar_usuarioLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminar_usuarioLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(eliminar_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminar_usuarioLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminar_usuarioLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(177, 177, 177))))
        );
        eliminar_usuarioLayout.setVerticalGroup(
            eliminar_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminar_usuarioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        jLabel18.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel18.setText("ALBUMS");

        jLabel19.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel19.setText("Crear ");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel25.setText("Listar");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel26.setText("Eliminar");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        panel_album.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));

        javax.swing.GroupLayout panel_albumLayout = new javax.swing.GroupLayout(panel_album);
        panel_album.setLayout(panel_albumLayout);
        panel_albumLayout.setHorizontalGroup(
            panel_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        panel_albumLayout.setVerticalGroup(
            panel_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout albumsLayout = new javax.swing.GroupLayout(albums.getContentPane());
        albums.getContentPane().setLayout(albumsLayout);
        albumsLayout.setHorizontalGroup(
            albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(albumsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(albumsLayout.createSequentialGroup()
                        .addGroup(albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel19)
                            .addComponent(jLabel26))
                        .addGap(34, 34, 34)
                        .addComponent(panel_album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, albumsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addGap(180, 180, 180)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        albumsLayout.setVerticalGroup(
            albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(albumsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(albumsLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel19)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel25)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel26))
                    .addGroup(albumsLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(52, 52, 52)
                        .addComponent(panel_album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel27.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel27.setText("Crear Album");

        jLabel28.setText("Nombre");

        jLabel29.setText("Artista");

        jButton4.setText("Crear");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crear_albumLayout = new javax.swing.GroupLayout(crear_album);
        crear_album.setLayout(crear_albumLayout);
        crear_albumLayout.setHorizontalGroup(
            crear_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crear_albumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(170, 170, 170))
            .addGroup(crear_albumLayout.createSequentialGroup()
                .addGroup(crear_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crear_albumLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(crear_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28))
                        .addGap(38, 38, 38)
                        .addGroup(crear_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_nombre_album, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_artista_album, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(crear_albumLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel27)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        crear_albumLayout.setVerticalGroup(
            crear_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_albumLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel27)
                .addGap(56, 56, 56)
                .addGroup(crear_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tf_nombre_album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(crear_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_artista_album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(24, 24, 24))
        );

        listar_album.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel30.setText("Listar album");
        listar_album.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        lista_album.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(lista_album);

        listar_album.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 358, 308));

        jLabel31.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel31.setText("Eliminar album");

        lista_album_e.setModel(                        new DefaultListModel());
        lista_album_e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_album_eMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(lista_album_e);

        jButton5.setText("Eliminar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout eliminar_albumLayout = new javax.swing.GroupLayout(eliminar_album);
        eliminar_album.setLayout(eliminar_albumLayout);
        eliminar_albumLayout.setHorizontalGroup(
            eliminar_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminar_albumLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel31)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(eliminar_albumLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminar_albumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(154, 154, 154))
        );
        eliminar_albumLayout.setVerticalGroup(
            eliminar_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminar_albumLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(25, 25, 25))
        );

        jLabel32.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel32.setText("Crear cancion");

        jLabel33.setText("Album");

        jLabel34.setText("Nombre");

        jLabel35.setText("Autor");

        jLabel36.setText("Duracion");

        jLabel37.setText("Genero");

        jButton6.setText("Crear cancion");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cancionLayout = new javax.swing.GroupLayout(cancion.getContentPane());
        cancion.getContentPane().setLayout(cancionLayout);
        cancionLayout.setHorizontalGroup(
            cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancionLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cancionLayout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(50, 50, 50)
                        .addComponent(tf_genero_cancion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancionLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(37, 37, 37)
                        .addComponent(tf_duracion_cancion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancionLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(59, 59, 59)
                        .addComponent(tf_autor_cancion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancionLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(44, 44, 44)
                        .addComponent(tf_nombre_cancion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancionLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(combo_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(136, 136, 136))
            .addGroup(cancionLayout.createSequentialGroup()
                .addGroup(cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cancionLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel32))
                    .addGroup(cancionLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cancionLayout.setVerticalGroup(
            cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel32)
                .addGap(57, 57, 57)
                .addGroup(cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(combo_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(tf_nombre_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tf_autor_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(tf_duracion_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(tf_genero_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(32, 32, 32))
        );

        jLabel38.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel38.setText("Explorar");
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel39.setText("Crear Playlist");

        jLabel40.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel40.setText("Ver Playlist");

        jLabel41.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel41.setText("Ver Favoritos");

        jLabel42.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel42.setText("Salir");

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login.getContentPane());
        Login.getContentPane().setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel42)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel38)
                .addGap(36, 36, 36)
                .addComponent(jLabel39)
                .addGap(34, 34, 34)
                .addComponent(jLabel40)
                .addGap(39, 39, 39)
                .addComponent(jLabel41)
                .addGap(37, 37, 37)
                .addComponent(jLabel42)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        cb_explorar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_explorarItemStateChanged(evt);
            }
        });

        jLabel43.setText("Seleccione album");

        lista_canciones.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(lista_canciones);

        jButton7.setText("Agregar a Playlist");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Agregar a Favoritos");

        javax.swing.GroupLayout explorarLayout = new javax.swing.GroupLayout(explorar.getContentPane());
        explorar.getContentPane().setLayout(explorarLayout);
        explorarLayout.setHorizontalGroup(
            explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(explorarLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton7)
                .addGap(29, 29, 29)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, explorarLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, explorarLayout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_explorar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, explorarLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        explorarLayout.setVerticalGroup(
            explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(explorarLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_explorar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(explorarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel1.setText("Cargar");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 414, 104, 45));

        jLabel2.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel2.setText("Guardar");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 351, 80, 45));

        jLabel3.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel3.setText("Usuarios");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 111, 104, 45));

        jLabel4.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel4.setText("Canciones");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 168, -1, 45));

        jLabel5.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel5.setText("Albums ");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 237, 80, 45));

        jLabel6.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        jLabel6.setText("Log in");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 294, 60, 45));

        jLabel17.setFont(new java.awt.Font("Marker Felt", 1, 48)); // NOI18N
        jLabel17.setText("REPRODUCTOR JJ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 360, 90));

        jLabel16.setIcon(new javax.swing.ImageIcon("/Users/jeansoto/Downloads/Colorful-Art-Desktop-Backgrounds.jpg")); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 590, 570));

        jMenu1.setText("Administracion");

        jMenuItem3.setText("Guardar como");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        try {
             aa.cargarArchivo(); 
            aa.setListaalbums(listaalbums);
            aa.escribirArchivo();
            //
            ap.cargarArchivo(); 
            ap.setListausuarios(listausuarios);
            ap.escribirArchivo();

            JOptionPane.showMessageDialog(this, "Guardado con exito");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        usuarios.setModal(true);
        usuarios.pack();
        usuarios.setLocationRelativeTo(this);
        usuarios.setVisible(true);


    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        crear_usuario.setSize(440, 440);
        crear_usuario.setLocation(5, 5);

        panel_usuario.removeAll();
        panel_usuario.add(crear_usuario, BorderLayout.CENTER);
        panel_usuario.revalidate();
        panel_usuario.repaint();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        listar_usuario.setSize(440, 440);
        listar_usuario.setLocation(5, 5);

        panel_usuario.removeAll();
        panel_usuario.add(listar_usuario, BorderLayout.CENTER);
        panel_usuario.revalidate();
        panel_usuario.repaint();

        lista_usuarios.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(lista_usuarios);

        DefaultListModel mod = (DefaultListModel) lista_usuarios.getModel();
        for (Usuario l : listausuarios) {
//                if (l.getUsername().equals(nick)) {
//                    mod.addElement("");
//                } else {
            mod.addElement(l.getUsername());
            // }

        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        eliminar_usuario.setSize(440, 440);
        eliminar_usuario.setLocation(5, 5);

        panel_usuario.removeAll();
        panel_usuario.add(eliminar_usuario, BorderLayout.CENTER);
        panel_usuario.revalidate();
        panel_usuario.repaint();

        lista_usuarios.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(lista_usuarios);

        DefaultListModel mod = (DefaultListModel) lista_usuarios_e.getModel();
        for (Usuario l : listausuarios) {
//                if (l.getUsername().equals(nick)) {
//                    mod.addElement("");
//                } else {
            mod.addElement(l.getUsername());
            // }

        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter fil = new FileNameExtensionFilter("examen2", "doo");
        JFileChooser jfc = new JFileChooser();
        jfc.setFileFilter(fil);
        int seleccion = jfc.showSaveDialog(this);
        FileWriter fw = null;
        File fichero = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                if (jfc.getFileFilter().getDescription().equals("examen2")) {
                    path = jfc.getSelectedFile().getPath() + ".doo";
                    fichero = new File(path);
                    ap.setListausuarios(listausuarios);
                    ap.escribirArchivo();
                } else {
                    fichero = jfc.getSelectedFile();
                }
                fw = new FileWriter(fichero);
                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente");
            } catch (Exception e) {
            }
            try {
                fw.close();
            } catch (Exception e) {
            }
            JOptionPane.showMessageDialog(this, "nuevo Guardado con exito");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
//        JFileChooser fc = new JFileChooser();
//        fc.setFileFilter(new FileNameExtensionFilter("examen", "doo"));
//        int opc = fc.showOpenDialog(this);
//        if (opc == JFileChooser.APPROVE_OPTION) {
//            File f = fc.getSelectedFile();
//            path = f.getPath();
//            try {
//                ap.cargarArchivo();
//                listausuarios = ap.getListausuarios();
//
//                JOptionPane.showMessageDialog(this, "Archivo abierto con exito");
//            } catch (Exception e) {
//                e.printStackTrace();
//                JOptionPane.showMessageDialog(this, "Ocurrio un error");
//            }
//
//        }
        ap.cargarArchivo();
        listausuarios =ap.getListausuarios();
        aa.cargarArchivo();
        listaalbums=aa.getListaalbums();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try {
            listausuarios.add(new Usuario(tf_nombre_usuario.getText(), Integer.parseInt(tf_edad_usuario.getText()), tf_username_usuario.getText(), pf_password_usuario.getText()));
            tf_nombre_usuario.setText("");
            tf_edad_usuario.setText("");
            tf_username_usuario.setText("");
            pf_password_usuario.setText("");
            JOptionPane.showMessageDialog(tf_nombre_usuario, "Creo usuario con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(tf_nombre_usuario, "ERROR");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void lista_usuarios_eMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_usuarios_eMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lista_usuarios_eMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            String s = lista_usuarios_e.getSelectedValue().toString();
            for (int i = 0; i < listausuarios.size(); i++) {
                if (listausuarios.get(i).getUsername().equals(s)) {
                    listausuarios.remove(i);
                }
            }

            JOptionPane.showMessageDialog(lista_usuarios_e, "Elimino exitosamente");
            lista_usuarios_e.setModel(new DefaultListModel());
            lista_usuarios_e.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    lista_usuarios_eMouseClicked(evt);
                }
            });

            DefaultListModel mod = (DefaultListModel) lista_usuarios_e.getModel();
            for (Usuario l : listausuarios) {
                mod.addElement(l.getUsername());
            }
            lista_usuarios_e.setModel(mod);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(lista_usuarios_e, "Ocurrio un error");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        crear_album.setSize(440, 440);
        crear_album.setLocation(5, 5);

        panel_album.removeAll();
        panel_album.add(crear_album, BorderLayout.CENTER);
        panel_album.revalidate();
        panel_album.repaint();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        listar_album.setSize(440, 440);
        listar_album.setLocation(5, 5);

        panel_album.removeAll();
        panel_album.add(listar_album, BorderLayout.CENTER);
        panel_album.revalidate();
        panel_album.repaint();

        lista_album.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(lista_album);
        
////          for (int i = 0; i < listaalbums.size(); i++) {
////           
////            DefaultTableModel modelo = (DefaultTableModel)tabla_albums.getModel();
////            modelo.addRow(listaalbums.toArray());
////            tabla_albums.setModel(modelo);
////            }
//        
//          Object [] a = new Array[listaalbums.size()];
//          for (int i = 0; i < listaalbums.size(); i++) {
//            a[i]=listaalbums.get(i).getNombre();
//            
//        }
//           DefaultTableModel modelo = (DefaultTableModel)tabla_albums.getModel();
//            modelo.addRow(a);
//            tabla_albums.setModel(modelo);
//          
////               DefaultTableModel model = (DefaultTableModel)tabla_albums.getModel();
////          Object array [] = listaalbums.toArray();
////          for (int i = 0; i < listaalbums.toArray().length-1; i++) {
////            model.addRow((Vector) array[i]);
////        }
////
        DefaultListModel mod = (DefaultListModel) lista_album.getModel();
        for (Album l : listaalbums) {
//                if (l.getUsername().equals(nick)) {
//                    mod.addElement("");
//                } else {
            mod.addElement(l.getNombre());
            // }

        }
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        eliminar_album.setSize(440, 440);
        eliminar_album.setLocation(5, 5);

        panel_album.removeAll();
        panel_album.add(eliminar_album, BorderLayout.CENTER);
        panel_album.revalidate();
        panel_album.repaint();

        lista_album_e.setModel(new DefaultListModel());
        lista_album_e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_album_eMouseClicked(evt);
            }
        });

        DefaultListModel mod = (DefaultListModel) lista_album_e.getModel();
        for (Album l : listaalbums) {
//                if (l.getUsername().equals(nick)) {
//                    mod.addElement("");
//                } else {
            mod.addElement(l.getNombre());
            // }

        }
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        listaalbums.add(new Album(tf_nombre_album.getText(), tf_artista_album.getText()));
        tf_nombre_album.setText("");
        tf_artista_album.setText("");
        JOptionPane.showMessageDialog(lista_usuarios_e, "Agrego album exitoso");

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) combo_cancion.getModel();
        for (Album ca : listaalbums) {
            modelo.addElement(ca.getNombre());

        }
        combo_cancion.setModel(modelo);
        
         DefaultComboBoxModel mode = (DefaultComboBoxModel) cb_explorar.getModel();
        for (Album ca : listaalbums) {
            mode.addElement(ca.getNombre());

        }
        cb_explorar.setModel(mode);
    }//GEN-LAST:event_jButton4MouseClicked

    private void lista_album_eMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_album_eMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lista_album_eMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        try {
            String s = lista_album_e.getSelectedValue().toString();
            for (int i = 0; i < listaalbums.size(); i++) {
                if (listaalbums.get(i).getNombre().equals(s)) {
                    listaalbums.remove(i);
                }
            }

            JOptionPane.showMessageDialog(lista_album_e, "Elimino exitosamente");
            lista_album_e.setModel(new DefaultListModel());
            lista_album_e.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    lista_usuarios_eMouseClicked(evt);
                }
            });

            DefaultListModel mod = (DefaultListModel) lista_album_e.getModel();
            for (Album l : listaalbums) {
                mod.addElement(l.getNombre());
            }
            lista_usuarios_e.setModel(mod);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(lista_album_e, "Ocurrio un error");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        albums.setModal(true);
        albums.pack();
        albums.setLocationRelativeTo(this);
        albums.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        cancion.setModal(true);
        cancion.pack();
        cancion.setLocationRelativeTo(this);
        cancion.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        try {
            listacanciones.add(new Cancion(combo_cancion.getSelectedItem().toString(), tf_nombre_cancion.getText(), tf_autor_cancion.getText(), Integer.parseInt(tf_duracion_cancion.getText()), tf_genero_cancion.getText()));
            JOptionPane.showMessageDialog(tf_nombre_cancion, "Creada con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(tf_nombre_cancion, "Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void cb_explorarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_explorarItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == 2) {
            String se = cb_explorar.getSelectedItem().toString();
            for (Album l : listaalbums) {
                System.out.println("for");
                if (l.getNombre().equals(se)) {
                    System.out.println("if");
                   
                    DefaultListModel mod = (DefaultListModel) lista_canciones.getModel();
                    
                        mod.addElement(l.canciones);
                    
                }
            }
        }
    }//GEN-LAST:event_cb_explorarItemStateChanged

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton7MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // TODO add your handling code here:
        explorar.setModal(true);
        explorar.pack();
        explorar.setLocationRelativeTo(this);
        explorar.setVisible(true);
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Login.setModal(true);
        Login.pack();
        Login.setLocationRelativeTo(this);
        Login.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        login.setModal(true);
        login.pack();
        login.setLocationRelativeTo(this);
        login.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Login;
    private javax.swing.JDialog albums;
    private javax.swing.JDialog cancion;
    private javax.swing.JComboBox cb_explorar;
    private javax.swing.JComboBox combo_cancion;
    private javax.swing.JPanel crear_album;
    private javax.swing.JPanel crear_usuario;
    private javax.swing.JPanel eliminar_album;
    private javax.swing.JPanel eliminar_usuario;
    private javax.swing.JDialog explorar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList lista_album;
    private javax.swing.JList lista_album_e;
    private javax.swing.JList lista_canciones;
    private javax.swing.JList lista_usuarios;
    private javax.swing.JList lista_usuarios_e;
    private javax.swing.JPanel listar_album;
    private javax.swing.JPanel listar_usuario;
    private javax.swing.JDialog login;
    private javax.swing.JPanel panel_album;
    private javax.swing.JPanel panel_usuario;
    private javax.swing.JPasswordField pf_password_usuario;
    private javax.swing.JTextField tf_artista_album;
    private javax.swing.JTextField tf_autor_cancion;
    private javax.swing.JTextField tf_duracion_cancion;
    private javax.swing.JTextField tf_edad_usuario;
    private javax.swing.JTextField tf_genero_cancion;
    private javax.swing.JTextField tf_nombre_album;
    private javax.swing.JTextField tf_nombre_cancion;
    private javax.swing.JTextField tf_nombre_usuario;
    private javax.swing.JTextField tf_username_usuario;
    private javax.swing.JDialog usuarios;
    // End of variables declaration//GEN-END:variables

    ArrayList<Usuario> listausuarios = new ArrayList();
    ArrayList<Album> listaalbums = new ArrayList();
    ArrayList<Cancion> listacanciones = new ArrayList();
    String path = "./examen2.doo";
      String ruta = "./albumes.doo";
    AdminUsuario ap = new AdminUsuario(path);
    AdminAlbum aa = new AdminAlbum(ruta);

}
